export const courses = [
    {
      id: 'C101',
      title: 'Introduction to Creative Writing',
      description: 'Explore the fundamentals of storytelling, character development, and narrative structure.',
      image: { id: 'course-1', hint: 'student writing' },
      instructor: 'Dr. Sarah Mitchell',
      category: 'Arts & Humanities',
      progress: 72,
      credits: 3,
      schedule: 'Mon/Wed 10:00 AM',
      status: 'In Progress',
    },
    {
      id: 'C102',
      title: 'Advanced Web Development',
      description: 'Dive deep into modern front-end frameworks and back-end architecture.',
      image: { id: 'course-2', hint: 'laptop code' },
      instructor: 'Prof. James Chen',
      category: 'Computer Science',
      progress: 45,
      credits: 4,
      schedule: 'Tue/Thu 2:00 PM',
      status: 'In Progress',
    },
    {
      id: 'C103',
      title: 'World History: Ancient Civilizations',
      description: 'A survey of major civilizations from prehistory to the medieval period.',
      image: { id: 'course-3', hint: 'history books' },
      instructor: 'Prof. Elena Rodriguez',
      category: 'History',
      progress: 100,
      credits: 3,
      schedule: 'Wed/Fri 11:00 AM',
      status: 'Completed',
    },
    {
      id: 'C104',
      title: 'Organic Chemistry I',
      description: 'An introduction to the structure, properties, and reactions of organic compounds.',
      image: { id: 'course-4', hint: 'science lab' },
      instructor: 'Dr. Kevin Park',
      category: 'Natural Sciences',
      progress: 30,
      credits: 4,
      schedule: 'Mon/Wed/Fri 9:00 AM',
      status: 'In Progress',
    },
    {
      id: 'C105',
      title: 'Fundamentals of Digital Art',
      description: 'Learn the core principles of digital painting, illustration, and design.',
      image: { id: 'course-5', hint: 'art canvas' },
      instructor: 'Ms. Aisha Johnson',
      category: 'Arts & Humanities',
      progress: 60,
      credits: 3,
      schedule: 'Tue/Thu 3:30 PM',
      status: 'In Progress',
    },
    {
      id: 'C106',
      title: 'Music Theory and Composition',
      description: 'Study the building blocks of music and create your own compositions.',
      image: { id: 'course-6', hint: 'grand piano' },
      instructor: 'Prof. Marco Rossi',
      category: 'Arts & Humanities',
      progress: 0,
      credits: 2,
      schedule: 'Fri 1:00 PM',
      status: 'Not Started',
    },
];

export const notes = [
    {
      id: 'N001',
      title: 'Lecture 1 - The Hero\'s Journey',
      course: 'Introduction to Creative Writing',
      courseId: 'C101',
      date: '2024-05-10',
      size: '2.3 MB',
      type: 'PDF',
      tags: ['lecture', 'narrative'],
    },
    {
      id: 'N002',
      title: 'React Hooks Explained',
      course: 'Advanced Web Development',
      courseId: 'C102',
      date: '2024-05-09',
      size: '5.1 MB',
      type: 'DOCX',
      tags: ['react', 'hooks', 'frontend'],
    },
    {
      id: 'N003',
      title: 'Study Guide - Midterm Exam',
      course: 'World History: Ancient Civilizations',
      courseId: 'C103',
      date: '2024-05-08',
      size: '800 KB',
      type: 'PDF',
      tags: ['midterm', 'study guide'],
    },
    {
      id: 'N004',
      title: 'Lab Report - Synthesis of Aspirin',
      course: 'Organic Chemistry I',
      courseId: 'C104',
      date: '2024-05-07',
      size: '1.5 MB',
      type: 'PDF',
      tags: ['lab', 'chemistry'],
    },
    {
      id: 'N005',
      title: 'Digital Color Theory Notes',
      course: 'Fundamentals of Digital Art',
      courseId: 'C105',
      date: '2024-05-05',
      size: '3.2 MB',
      type: 'PDF',
      tags: ['design', 'color'],
    },
];
  
export const resources = [
  {
    title: 'The Purdue Online Writing Lab (OWL)',
    description: 'A comprehensive resource for academic writing, grammar, and citation styles.',
    type: 'Website',
    category: 'Writing',
    href: 'https://owl.purdue.edu/',
    featured: true,
  },
  {
    title: 'MDN Web Docs',
    description: 'The ultimate resource for web developers, maintained by Mozilla.',
    type: 'Documentation',
    category: 'Computer Science',
    href: 'https://developer.mozilla.org/',
    featured: true,
  },
  {
    title: 'Khan Academy',
    description: 'Free online courses, lessons, and practice for a wide range of subjects.',
    type: 'Platform',
    category: 'All Subjects',
    href: 'https://www.khanacademy.org/',
    featured: false,
  },
  {
    title: 'Project Gutenberg',
    description: 'A library of over 60,000 free eBooks, ideal for literature studies.',
    type: 'eBooks',
    category: 'Literature',
    href: 'https://www.gutenberg.org/',
    featured: false,
  },
  {
    title: 'Wolfram Alpha',
    description: 'A computational knowledge engine for math, science, and research.',
    type: 'Tool',
    category: 'Mathematics',
    href: 'https://www.wolframalpha.com/',
    featured: false,
  },
  {
    title: 'Google Scholar',
    description: 'Search scholarly articles, theses, books, and conference papers.',
    type: 'Search Engine',
    category: 'Research',
    href: 'https://scholar.google.com/',
    featured: false,
  },
];
